# Generated by Django 2.1.4 on 2022-07-20 22:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLInstagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('short_lived_access_token', models.TextField(blank=True)),
                ('long_lived_access_token', models.TextField(blank=True)),
                ('user_id', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'ml_instagram',
            },
        ),
        migrations.CreateModel(
            name='MLInstagramSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'ml_instagram_setting',
            },
        ),
        migrations.AddField(
            model_name='mlinstagram',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_instagram.MLInstagramSetting'),
        ),
    ]
